# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournament_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rule',
            field=models.URLField(default='www.estavos.com', verbose_name='Link para download do regulamento'),
            preserve_default=False,
        ),
    ]
