# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_auto_20171129_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex.: 1º Lote', max_length=50, verbose_name='Identificador')),
                ('full', models.DecimalField(decimal_places=2, default='30.00', max_digits=7, verbose_name='Valor da inteira')),
                ('half', models.DecimalField(decimal_places=2, default='15.00', help_text='Opcional', max_digits=7, verbose_name='Valor da meia')),
                ('limit_date', models.DateTimeField(verbose_name='Válido para inscrições realizadas até')),
                ('active', models.BooleanField(verbose_name='Ativo?')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
        ),
        migrations.AlterField(
            model_name='prize',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nome do prêmio'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='price',
            field=models.DecimalField(decimal_places=2, default='25.00', max_digits=7, verbose_name='Valor da inscrição'),
        ),
        migrations.AddField(
            model_name='inscriptionprice',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_prices', to='tournaments.Tournament'),
        ),
    ]
