# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_auto_20171129_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionprice',
            name='half',
            field=models.DecimalField(blank=True, decimal_places=2, default='15.00', help_text='Opcional', max_digits=7, null=True, verbose_name='Valor da meia'),
        ),
    ]
